# Generated by Django 4.2.11 on 2024-05-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_peopleinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleinfo',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, '男'), (1, '女')], default=1),
        ),
    ]
